#! /bin/sh
# upgrade script

mkdir -p /mnt/hd
mount /dev/mmcblk1p2 /mnt/hd

cp /mnt/iso/osd /mnt/hd/usr/bin
chmod +x /mnt/hd/usr/bin/osd

cp /mnt/iso/s90osd /mnt/hd/etc/rc5.d/S90osd
chmod +x /mnt/hd/etc/rc5.d/S90osd

sync && sync

cd /mnt/iso

/mnt/iso/fwupg
