#!/bin/sh


echo -------------------------------
echo - Update image copier utility -
echo -------------------------------

echo mounting partition 3
if ! mkdir -p /mnt/p3; then
  echo ERROR creating /mnt/p3
  exit -1
fi

if ! mount -t vfat /dev/mmcblk1p3 /mnt/p3; then
  echo ERROR mounting partition 3
  exit -1
fi

echo coping image and md5
if ! cp /mnt/usb/recovery/image /mnt/p3; then
  echo ERROR coping image file
  umount /mnt/p3
  exit -1
fi

if ! cp /mnt/usb/recovery/image.md5 /mnt/p3; then
  echo ERROR coping md5 file
  umount /mnt/p3
  exit -1
fi


echo verify md5
cd /mnt/p3/
if ! md5sum -c image.md5; then
  echo ERROR verify md5 fail, remove all
  rm /mnt/p3/image
  rm /mnt/p3/image.md5
  rm /mnt/p3/local.md5
  cd ~
  umount /mnt/p3
  exit -1
fi
echo umount partions 3
cd ~
umount /mnt/p3

echo mounting partition 1
if ! mkdir -p /mnt/p1; then
  echo ERROR creating /mnt/p1
  exit -1
fi
if ! mount -t vfat /dev/mmcblk1p1 /mnt/p1; then
  echo ERROR mounting partition 1
  exit -1
fi

echo creating boot.scr
rm boot.script
echo "recovery FAT mmc 1:3 image" > boot.script
mkimage -T script -C none -n "recovery/update script" -d boot.script /mnt/p1/boot.scr

echo umount partions 1
umount /mnt/p1

sync && sync

echo done

exit 0